version: "3.9"
services:
  suricata:
    image: jasonish/suricata
    volumes:
      - suricata-data:/var/log/suricata
      - suricata-data:/etc/suricata
      - suricata-data:/var/lib/suricata
    network_mode: host
    command: -i enp5s2
    cap_add:
      - net_admin
      - sys_nice
    restart: always
  filebeat:
    build:
      context: extensions/filebeat/
      args:
        ELK_VERSION: $ELK_VERSION
    # Run as 'root' instead of 'filebeat' (uid 1000) to allow reading
    # 'docker.sock' and the host's filesystem.
    user: root
    command:
      # Log to stderr.
      - -e
      # Disable config file permissions checks. Allows mounting
      # 'config/filebeat.yml' even if it's not owned by root.
      # see: https://www.elastic.co/guide/en/beats/libbeat/current/config-file-permissions.html
      - --strict.perms=false
    volumes:
      - suricata-data:/var/log/suricata:ro
    networks:
      - elk
volumes:
  suricata-data:
networks:
  elk:
    external: true
    name: docker-elk_elk
